name: Build and Release for Windows

on: push

jobs:
  build_release:
    runs-on: windows-latest

    steps:
      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@d8610e2b41c6d0f0c3b4c46dad8df0fd826c68e1 #v1

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get short commit SHA
        run: echo SHORT_SHA=$(git rev-parse --short HEAD) >> $env:GITHUB_ENV

      - name: Install QT
        uses: jurplel/install-qt-action@64bdb64f2c14311d23733a8463e5fcbc65e8775e #v3
        with:
          version: 6.3.1
          cache: true

      - name: Make build directory
        run: mkdir build

      - name: Run CMake
        run: cd build && cmake ..

      - name: Run MSBuild
        run: cd build && msbuild wake_on_lan.sln -property:Configuration=Release

      - name: Gather build artifacts
        run: |
          cd build/Release/
          mkdir wake_on_lan
          mv wake_on_lan.exe wake_on_lan/
          windeployqt --release --no-translations --no-system-d3d-compiler --no-opengl-sw wake_on_lan/wake_on_lan.exe
          Compress-Archive -Path wake_on_lan/ -DestinationPath wake_on_lan-${{ env.SHORT_SHA }}.zip

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 #v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/Release/wake_on_lan-${{ env.SHORT_SHA }}.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
