name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI/CD for Windows']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@e9fa2f582c0ebbe2e263fd18fad744d52e0b0203 #v1
      with:
        artifact: test-results
        name: JUnit Appium Tests
        path: '*.xml'
        reporter: java-junit
