name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI/CD for Windows']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 #v1
      with:
        artifact: test-results
        name: JUnit Appium Tests
        path: *.xml
        reporter: java-junit
